# Generated by Django 5.0 on 2026-02-25 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_time', models.TimeField()),
                ('was_taken', models.BooleanField(default=False)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='medications.medication')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
