# Generated by Django 4.2.28 on 2026-02-26 07:13

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_medicationreminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(max_length=100, validators=[core.validators.validate_no_html]),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=200, validators=[core.validators.validate_no_html]),
        ),
    ]
