# Generated by Django 4.2.28 on 2026-03-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_assigned_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_digest_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
