# Generated by Django 5.2.11 on 2026-02-24 11:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('severity', models.IntegerField(help_text='Severity on scale of 1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('related_medications', models.ManyToManyField(blank=True, related_name='symptoms', to='medications.medication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-logged_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='symptoms_sy_user_id_a107b9_idx'), models.Index(fields=['user', 'name'], name='symptoms_sy_user_id_a7abc0_idx')],
            },
        ),
    ]
