# Generated by Django 4.2.28 on 2026-02-26 07:13

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0002_moodlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='name',
            field=models.CharField(max_length=200, validators=[core.validators.validate_no_html]),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='notes',
            field=models.TextField(blank=True, validators=[core.validators.validate_no_html]),
        ),
    ]
